export const SELECTED_ACTIVITY_REQUEST = "SELECTED_ACTIVITY_REQUEST";
export const SELECTED_ACTIVITY_FAILURE = "SELECTED_ACTIVITY_FAILURE";

export const GET_SELECTED_ACTIVITY = "GET_SELECTED_ACTIVITY";
export const GET_ALL_SELECTED_ACTIVITY = "GET_ALL_SELECTED_ACTIVITY";
export const UPDATE_SELECTED_ACTIVITY = "UPDATE_SELECTED_ACTIVITY";
export const DELETE_SELECTED_ACTIVITY = "DELETE_SELECTED_ACTIVITY";
