export const ACTIVITY_REQUEST = "ACTIVITY_REQUEST";
export const ACTIVITY_FAILURE = "ACTIVITY_FAILURE";

export const GET_ACTIVITY = "GET_ACTIVITY";
export const PATCH_ACTIVITY = "PATCH_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
