export const GET_ACTIVITY="GET_ACTIVITY";
export const GET_ACTIVITY_FAILURE="GET_ACTIVITY_FAILURE";
export const POST_ACTIVITY="POST_ACTIVITY";
export const UPDATE_ACTIVITY="UPDATE_ACTIVITY";
export const DELETE_ACTIVITY="DELETE_ACTIVITY";
