
export const GET_USER = "GET_USER";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const POST_USER = "POST_USER";
export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_FAILURE = "POST_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
