export const CHALLENGE_REQUEST = "CHALLENGE_REQUEST";
export const CHALLENGE_FAILURE = "CHALLENGE_FAILURE";

export const GET_CHALLENGE = "GET_CHALLENGE";
export const PATCH_CHALLENGE = "PATCH_CHALLENGE";
export const DELETE_CHALLENGE = "DELETE_CHALLENGE";
