export const CHALLENGE_REQUEST = "CHALLENGE_REQUEST";
export const CHALLENGE_FAILURE = "CHALLENGE_FAILURE";

export const GET_CHALLENGE_SUCCESS = "GET_CHALLENGE_SUCCESS";
export const POST_CHALLENGE_SUCCESS = "POST_CHALLENGE_SUCCESS";
