export const FRIEND_REQUEST = "FRIEND_REQUEST";
export const FRIEND_FAILURE = "FRIEND_FAILURE";

export const GET_FRIEND_SUCCESS = "GET_FRIEND_SUCCESS";
export const POST_FRIEND_SUCCESS = "POST_FRIEND_SUCCESS";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const PATCH_FRIEND_SUCCESS = "PATCH_FRIEND_SUCCESS";
