export const FRIEND_REQUEST = "FRIEND_REQUEST";
export const FRIEND_FAILURE = "FRIEND_FAILURE";

export const GET_FRIEND = "GET_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";
export const PATCH_FRIEND = "PATCH_FRIEND";
